#!/bin/sh
set -eu

echo "Requirements (on debian):"
echo "autoconf libncurses5-dev libssl-dev libtokyocabinet-dev libsasl2-dev"
echo "links"

cd
mkdir -p sandbox

if [ ! -d sandbox/neomutt ]; then
  git clone https://github.com/neomutt/neomutt.git sandbox/neomutt
else
  git -C sandbox/neomutt pull
fi

cd sandbox/neomutt

./prepare \
 --with-ssl --with-sasl \
 --enable-hcache \
 --enable-imap --enable-smtp \
 --enable-sidebar >/dev/null

make -j3 >/dev/null

cd ~/bin
ln -sf ../sandbox/neomutt/mutt mutt

