#!/bin/sh
set -eu

install_it() {
  bina_install "casey/just"
  # cargo install just
}

# This can probably be removed next time you look here
export JUST_CHOOSER="fzf --preview 'just --show {}'"

. ~/.lib/sh/stubexec.sh
