#!/bin/sh
set -eu

install_it() {
  cpm install -g \
    Reply \
    experimentals \
    B::Keywords \
    Carp::Always \
    Class::Refresh \
    Data::Printer \
    Data::Printer::Filter::JSON \
    Data::Printer::Filter::URI \
    Path::Tiny \
    Pry \
    Term::ReadLine::Gnu
}

. ~/.lib/sh/stubexec.sh
