#!/bin/sh
set -eu

age_limit=180

install_it() {
  local scratch="$(mktemp -d)"
  trap 'rm -rf -- "$scratch"' EXIT
  git clone --depth=1 "https://git.sr.ht/~sircmpwn/scdoc" "$scratch"
  make -C "$scratch" install PREFIX="$HOME/.local"
  rm -rf -- "$scratch"
}

. ~/.lib/sh/stubexec.sh
