#!/bin/sh
set -eu

age_limit=30
nix_ref='nixpkgs#tectonic'

install_it() {
  mkdir -p ~/.local/bin
  cd ~/.local/bin
  curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net |
    sh
  cd -
  asdf reshim || :
}

. ~/.lib/sh/stubexec.sh
